### ISSUE TITLE
Problem when reading file with GeoDataFrames package

### ISSUE THREAD

**Issue by martinmestre** [yeesian/ArchGDAL.jl#224] opened 2021-07-26 15:42 UTC
Hello @yeesian et al.,
when executing the line:
```
data=GeoDataFrames.read(graph_file)
```
the output is:

```
MethodError: Cannot `convert` an object of type 
  ArchGDAL.IGeometry{wkbMultiPolygon} to an object of type ArchGDAL.IGeometry{wkbPolygon}
```

Could you please help me to solve this problem ?
Thank you very much,
Martín

**Comment by visr** [comment] 2021-07-26 17:58
I'll close this as a duplicate of #223

**Closed by visr** 2021-07-26 17:58 UTC
